FROM php:7.2

RUN apt-get update -y && apt-get install -y openssl zip unzip git
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN docker-php-ext-install pdo mbstring
WORKDIR /app
COPY . /app

RUN git clone https://github.com/buddy-works/laravel-first-steps.git
run ls
RUN cd laravel-first-steps && composer install


RUN cd laravel-first-steps/public && ls
COPY /laravel-first-steps/public/index.php /var/www/html/



